name: Release

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Node env
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Create build artifact
        uses: actions/upload-artifact@master
        with:
          name: build-output
          path: dist/
      - name: Publish dist to NPM
        run: |
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
